image: node:18
pages:  
  stage: deploy  
  before_script:
  - npm -v
  # - pm2 status
  script:
  - cp -r -u * /var/www/bashkent.projectview.uz
  - cd /var/www/bashkent.projectview.uz
  - ls -la
  # - export PM2_HOME=/home/ubuntu/.pm2
  - pm2 status
  # - pm2 delete bashkent
  # - pm2 status
  # - pm2 restart bashkent 
  # - pm2 delete bashkent
  # - NODE_OPTIONS="--max-old-space-size=1024" npm run build
  # - pm2 restart bashkent
  # - PORT=3001 pm2 start .output/server/index.mjs --name bashkent
  artifacts:
    paths:
    - ./*
  only:
  - main